# The fleet.yaml is always at the root
# relative to the path of the GitRepo

namespace: bsctl

targetCustomizations:
  - name: dev-internal
    clusterSelector:
      matchLabels:
        environment: dev-internal
    helm:
      values:
        replicaCount: 6

  - name: prod-internal
    clusterSelector:
      matchLabels:
        environment: prod-internal
    helm:
      values:


