# The fleet.yaml is always at the root
# relative to the path of the GitRepo

namespace: bsctl

targetCustomizations:
  - name: dev-internal
    clusterSelector:
      matchLabels:
        environment: dev-internal
    helm:
      valueFiles:
      - ./values-dev.yaml

  - name: prod-internal
    clusterSelector:
      matchLabels:
        environment: prod-internal
    helm:
      values:
        replicaCount: 2

