apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inibitios-app-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: azurekv-net-dev
    kind: ClusterSecretStore
  target:
    name: inibitios-app-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/opaque
  data:
  - secretKey: secretKey
    remoteRef:
      key: inibitios-app-secretkey
  - secretKey: guiAdminName
    remoteRef:
      key: inibitios-app-guiadminname
  - secretKey: guiAdminPassword
    remoteRef:
      key: inibitios-app-guiadminpassword