apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: inibitios-regcred
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: azurekv-net-dev
    kind: ClusterSecretStore
  target:
    name: regcred
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: inibitios-regcred